package uz.ilmnajot.organisation_task.exception;

public class AlreadyExistFoundException extends RuntimeException {

    public AlreadyExistFoundException(String message) {
        super(message);

    }
}
